# Generated by Django 6.0.2 on 2026-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0004_unique_pending_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='duration_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours (if service is per hour) or days (if per day) for this invoice.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default hours (if per hour) or days (if per day) for estimates.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'Per hour'), ('daily', 'Per day'), ('entire_job', 'Entire job (fixed rate)')], default='entire_job', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='For technicians: separate multiple skills with commas (e.g. Plumbing, Electrical)', max_length=255),
        ),
    ]
