# Generated by Django 6.0.2 on 2026-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0005_service_price_type_and_invoice_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='default_duration',
        ),
        migrations.AddField(
            model_name='job',
            name='duration_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours (if service is per hour) or days (if per day). Used for invoice calculation.', max_digits=8, null=True),
        ),
    ]
