# Generated by Django 6.0.2 on 2026-02-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0006_duration_on_job_remove_from_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subcategories', models.JSONField(default=list, help_text='List of subcategory names, e.g. ["Plumbing", "Electrical"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='artisans.servicecategory'),
        ),
        migrations.CreateModel(
            name='PreDefinedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='e.g. Plumber, Electrician', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_type', models.CharField(choices=[('per_hour', 'Per hour'), ('daily', 'Per day'), ('entire_job', 'Entire job (fixed rate)')], default='entire_job', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_services', to='artisans.servicecategory')),
            ],
            options={
                'unique_together': {('category', 'provider_name', 'name')},
            },
        ),
    ]
