# Generated by Django 6.0.2 on 2026-02-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_categories_and_predefined_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='artisans.servicecategory')),
            ],
            options={
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='servicetype',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_types', to='artisans.servicesubcategory'),
        ),
        migrations.RemoveField(
            model_name='predefinedservice',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='predefinedservice',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predefined_services', to='artisans.servicesubcategory'),
        ),
    ]
