# Generated by Django 6.0.2 on 2026-02-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0008_category_subcategory_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
