# Generated by Django 6.0.2 on 2026-02-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0009_remove_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
