# Generated by Django 6.0.2 on 2026-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0010_remove_job_description_remove_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_plan',
            field=models.CharField(choices=[('full', 'Full payment'), ('partial', 'Partial payment'), ('installments', 'Installments')], default='full', max_length=20),
        ),
    ]
