# Generated by Django 6.0.2 on 2026-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0011_invoice_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='If set, invoices will show 15%% VAT (subtotal + VAT = total).'),
        ),
    ]
