# Generated by Django 6.0.2 on 2026-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0012_organization_vat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map and distance (geocode from address or set manually).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map and distance.', max_digits=9, null=True),
        ),
    ]
