# Generated by Django 6.0.2 on 2026-02-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0013_organization_lat_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking', 'New booking'), ('other', 'Other')], default='booking', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_notifications', to='artisans.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
